version: "3"
services:
  cheeseria-ui:
    container_name: cheeseria-app
    restart: always
    build: ./cheeseria-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - cheeseria-app
  cheeseria-api:
    container_name: cheeseria-back-end
    restart: always
    build: ./cheeseria-back-end
    ports:
      - "4000:4000"
    networks:
      - cheeseria-app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0-focal
    ports:
      - "27017:27017"
    networks:
      - cheeseria-app
    volumes:
      - mongo-data:/data/db
networks:
  cheeseria-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
